welcome:
  message: Hello Guys Welcome


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin@123
    url: jdbc:mysql://localhost/springadmin?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:8766

logging:
  file:
    name: product-service.log
    max-history: 20
    max-size: 20MB

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



