
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
welcome:
  message: welcome to default environment from config sever

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin@123
    url: jdbc:mysql://localhost/springadmin?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  application:
    name: ConfigClient

  boot:
    admin:
      client:
        url: http://localhost:8767

logging:
  file:
    name: product-service.log
    max-history: 20
    max-size: 20MB

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

